export const products = [
  {
    id: 1,
    name: "White Fila",
    price: 59.99,
    category: "Sneakers",
    inStock: true,
    rating: 4.5,
    size: 40,
    url: "/one.jpg",
  },
  {
    id: 2,
    name: "Jungle Green Boots",
    price: 89.99,
    category: "Electronics",
    inStock: true,
    rating: 4.7,
    size: 39,
    url: "/two.jpg",
  },
  {
    id: 3,
    name: "Blue Ghost Nike",
    price: 19.99,
    category: "Fitness",
    inStock: false,
    rating: 4.2,
    size: 39,
    url: "/three.jpg",
  },
  {
    id: 4,
    name: "Black Orange Dunks",
    price: 12.99,
    category: "Kitchen",
    inStock: true,
    rating: 4.8,
    size: 38,
    url: "/four.jpg",
  },
  {
    id: 5,
    name: "Black and White Stripe",
    price: 29.99,
    category: "Electronics",
    inStock: true,
    rating: 4.4,
    size: 22,
    url: "/five.jpg",
  },
  {
    id: 6,
    name: "African Print Heels",
    price: 49.99,
    category: "Fitness",
    inStock: false,
    rating: 4.6,
    size: 33,
    url: "/six.jpg",
  },
  {
    id: 7,
    name: "Charcoal Nike",
    price: 149.99,
    category: "Electronics",
    inStock: true,
    rating: 4.3,
    size: 50,
    url: "/seven.jpg",
  },
  {
    id: 8,
    name: "Pink Pony",
    price: 9.99,
    category: "Fitness",
    inStock: true,
    rating: 4.9,
    size: 43,
    url: "/eight.jpg",
  },
  {
    id: 20,
    name: "Pink Pony",
    price: 9.99,
    category: "Fitness",
    inStock: true,
    rating: 4.9,
    size: 43,
    url: "/eight.jpg",
  },
  {
    id: 21,
    name: "Pink Pony",
    price: 9.99,
    category: "Fitness",
    inStock: true,
    rating: 4.9,
    size: 43,
    url: "/eight.jpg",
  },
  {
    id: 22,
    name: "Pink Pony",
    price: 9.99,
    category: "Fitness",
    inStock: true,
    rating: 4.9,
    size: 43,
    url: "/eight.jpg",
  },
  {
    id: 23,
    name: "Pink Pony",
    price: 9.99,
    category: "Fitness",
    inStock: true,
    rating: 4.9,
    size: 43,
    url: "/eight.jpg",
  },
  {
    id: 24,
    name: "Pink Pony",
    price: 9.99,
    category: "Fitness",
    inStock: true,
    rating: 4.9,
    size: 43,
    url: "/eight.jpg",
  },
  {
    id: 25,
    name: "Rainbow Yours",
    price: 24.99,
    category: "Home",
    inStock: false,
    rating: 4.6,
    size: 18,
    url: "/nine.jpg",
  },

  {
    id: 11,
    name: "Coal Miner",
    price: 17.99,
    category: "Home",
    inStock: true,
    rating: 4.8,
    size: 29,
    url: "/eleven.jpg",
  },
  {
    id: 12,
    name: "Coal Miner",
    price: 17.99,
    category: "Home",
    inStock: true,
    rating: 4.8,
    size: 29,
    url: "/eleven.jpg",
  },
  {
    id: 13,
    name: "Coal Miner",
    price: 17.99,
    category: "Home",
    inStock: true,
    rating: 4.8,
    size: 29,
    url: "/eleven.jpg",
  },
  {
    id: 14,
    name: "Coal Miner",
    price: 17.99,
    category: "Home",
    inStock: true,
    rating: 4.8,
    size: 29,
    url: "/eleven.jpg",
  },
  {
    id: 15,
    name: "Coal Miner",
    price: 17.99,
    category: "Home",
    inStock: true,
    rating: 4.8,
    size: 29,
    url: "/eleven.jpg",
  },
];
